/* ------------------------------------------------------------------ */
/* WARNING: relative order of tokens is important. */

DEF(TOK_nativestdcall, "nativecall")
DEF(TOK_nativethiscall, "nativethiscall")
DEF(TOK_naked, "naked")

/* register */
 DEF_ASM(r00)
 DEF_ASM(r08)
 DEF_ASM(r10)
 DEF_ASM(r18)
 DEF_ASM(r20)
 DEF_ASM(r28)
 DEF_ASM(r30)
 DEF_ASM(r38)
 DEF_ASM(r40)
 DEF_ASM(r48)
 DEF_ASM(r50)
 DEF_ASM(r58)
 DEF_ASM(r60)
 DEF_ASM(r68)
 DEF_ASM(r70)
 DEF_ASM(r78)
 DEF_ASM(r80)
 DEF_ASM(r88)
 DEF_ASM(r90)
 DEF_ASM(r98)
 DEF_ASM(rA0)
 DEF_ASM(rA8)
 DEF_ASM(rB0)
 DEF_ASM(rB8)
 DEF_ASM(rC0)
 DEF_ASM(rC8)
 DEF_ASM(rD0)
 DEF_ASM(rD8)
 DEF_ASM(rE0)
 DEF_ASM(rE8)
 DEF_ASM(rF0)
 DEF_ASM(rF8)
 DEF_ASM(rbp)
 DEF_ASM(rsp)
 DEF_ASM(rip)

/* ops */
 DEF_ASM(movb)
 DEF_ASM(movw)
 DEF_ASM(movl)
 DEF_ASM(movq)
 DEF_ASM(movsbl)
 DEF_ASM(movswl)
 DEF_ASM(movslq)
 DEF_ASM(movzbl)
 DEF_ASM(movzwl)
 DEF_ASM(movzlq)
 DEF_ASM(lea)
 DEF_ASMTEST(set)
 DEF_ASM(ldsp)
 DEF_ASM(ldbp)
 DEF_ASM(stsp)
 DEF_ASM(stbp)
 DEF_ASM(enter)
 DEF_ASM(retn)
 DEF_ASMTEST(j)
 DEF_ASM(add)
 DEF_ASM(sub)
 DEF_ASM(and)
 DEF_ASM(call)
 DEF_ASM(ncall0)
 DEF_ASM(ncall)
 DEF_ASM(ntcall)
 DEF_ASM(pushl)
 DEF_ASM(pushq)
 DEF_ASM(push32)
 DEF_ASM(imull)
 DEF_ASM(imulq)
 DEF_ASM(divl)
 DEF_ASM(divq)
 DEF_ASM(udivl)
 DEF_ASM(udivq)
 DEF_ASM(modl)
 DEF_ASM(modq)
 DEF_ASM(umodl)
 DEF_ASM(umodq)
 DEF_ASM(shll)
 DEF_ASM(shlq)
 DEF_ASM(shrl)
 DEF_ASM(shrq)
 DEF_ASM(sarl)
 DEF_ASM(sarq)
 DEF_ASM(jmp)
 DEF_ASM(jmps)
 DEF_ASM(addl)
 DEF_ASM(addq)
 DEF_ASM(orl)
 DEF_ASM(orq)
 DEF_ASM(adcl)
 DEF_ASM(adcq)
 DEF_ASM(sbbl)
 DEF_ASM(sbbq)
 DEF_ASM(andl)
 DEF_ASM(andq)
 DEF_ASM(subl)
 DEF_ASM(subq)
 DEF_ASM(xorl)
 DEF_ASM(xorq)
 DEF_ASM(cmpl)
 DEF_ASM(cmpq)
 DEF_ASM(fcmps)
 DEF_ASM(fcmpd)
 DEF_ASM(fucmps)
 DEF_ASM(fucmpd)
 DEF_ASM(fadds)
 DEF_ASM(faddd)
 DEF_ASM(fsubs)
 DEF_ASM(fsubd)
 DEF_ASM(fmuls)
 DEF_ASM(fmuld)
 DEF_ASM(fdivs)
 DEF_ASM(fdivd)
 DEF_ASM(fcvtl2s)
 DEF_ASM(fcvtl2d)
 DEF_ASM(fcvtq2s)
 DEF_ASM(fcvtq2d)
 DEF_ASM(fcvts2l)
 DEF_ASM(fcvtd2l)
 DEF_ASM(fcvts2q)
 DEF_ASM(fcvtd2q)
 DEF_ASM(fcvtuq2s)
 DEF_ASM(fcvtuq2d)
 DEF_ASM(fcvts2uq)
 DEF_ASM(fcvtd2uq)
 DEF_ASM(fcvts2d)
 DEF_ASM(fcvtd2s)

 /* generic asm ops */
#define ALT(x)
#define DEF_ASM_OP0(name, opcode) DEF_ASM(name)
#define DEF_ASM_OP0L(name, opcode, group, instr_type)
#define DEF_ASM_OP1(name, opcode, group, instr_type, op0)
#define DEF_ASM_OP2(name, opcode, group, instr_type, op0, op1)
# include "svm-asm.h"

#define ALT(x)
#define DEF_ASM_OP0(name, opcode)
#define DEF_ASM_OP0L(name, opcode, group, instr_type) DEF_ASM(name)
#define DEF_ASM_OP1(name, opcode, group, instr_type, op0) DEF_ASM(name)
#define DEF_ASM_OP2(name, opcode, group, instr_type, op0, op1) DEF_ASM(name)
# include "svm-asm.h"
